config/routes.rb
Rails.application.routes.draw do
  resources :decisions
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/decision.rb
class Decision < ApplicationRecord
  belongs_to :project
end

app/models/input.rb
class DecisionInputs < ApplicationRecord
	belongs_to :decision
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :decisions, dependent: :destroy, inverse_of: :project
  accepts_nested_attributes_for :decisions, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :set_decision, only: %i[ show edit update destroy ]

  # GET /decisions or /decisions.json
  def index
    @decisions = Decision.all
  end

  # GET /decisions/1 or /decisions/1.json
  def show
  end

  # GET /decisions/new
  def new
    @decision = Decision.new
  end

  # GET /decisions/1/edit
  def edit
  end

  # POST /decisions or /decisions.json
  def create
    @decision = Decision.new(decision_params)

    respond_to do |format|
      if @decision.save
        format.html { redirect_to decision_url(@decision), notice: "Decision was successfully created." }
        format.json { render :show, status: :created, location: @decision }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decisions/1 or /decisions/1.json
  def update
    respond_to do |format|
      if @decision.update(decision_params)
        format.html { redirect_to decision_url(@decision), notice: "Decision was successfully updated." }
        format.json { render :show, status: :ok, location: @decision }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decisions/1 or /decisions/1.json
  def destroy
    @decision.destroy

    respond_to do |format|
      format.html { redirect_to decisions_url, notice: "Decision was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_decision
      @decision = Decision.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def decision_params
      params.require(:decision).permit(:input, :input_type, :project_id)
    end
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController

	def new 
		@values = Decision.pluck(:column_name)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.decisions.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(
        :title,
        decisions_attributes: [:id, :input, :input_type, :_destroy]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/decisions/_decision.html.erb
<div id="<%= dom_id decision %>">
  <p>
    <strong>Input:</strong>
    <%= decision.input %>
  </p>

  <p>
    <strong>Input type:</strong>
    <%= decision.input_type %>
  </p>

  <p>
    <strong>Result:</strong>
    <%= decision.result %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= decision.project_id %>
  </p>

</div>

app/views/decisions/_form.html.erb
<%= form_with(model: decision) do |form| %>
  <% if decision.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(decision.errors.count, "error") %> prohibited this decision from being saved:</h2>

      <ul>
        <% decision.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :input, style: "display: block" %>
    <%= form.text_field :input %>
  </div>

  <div>
    <%= form.label :input_type, style: "display: block" %>
    <%= form.text_field :input_type %>
  </div>

  <div>
    <%= form.label :result, style: "display: block" %>
    <%= form.text_field :result %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/decisions/edit.html.erb
<h1>Editing decision</h1>

<%= render "form", decision: @decision %>

<br>

<div>
  <%= link_to "Show this decision", @decision %> |
  <%= link_to "Back to decisions", decisions_path %>
</div>

app/views/decisions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Decisions</h1>

<div id="decisions">
  <% @decisions.each do |decision| %>
    <%= render decision %>
    <p>
      <%= link_to "Show this decision", decision %>
    </p>
  <% end %>
</div>

<%= link_to "New decision", new_decision_path %>

app/views/decisions/new.html.erb
<h1>New decision</h1>

<%= render "form", decision: @decision %>

<br>

<div>
  <%= link_to "Back to decisions", decisions_path %>
</div>

app/views/decisions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @decision %>

<div>
  <%= link_to "Edit this decision", edit_decision_path(@decision) %> |
  <%= link_to "Back to decisions", decisions_path %>

  <%= button_to "Destroy this decision", @decision, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedAttributes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, data: {
  controller: 'nested-form',
  nested_form_wrapper_selector_value: '.nested-form-wrapper'
}) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <template data-nested-form-target="template">
    <%= form.fields_for :decisions, Decision.new, child_index: 'NEW_RECORD' do |decision_fields| %>
      <%= render "projects/project_decision_form", f: decision_fields %>
    <% end %>
  </template>

  <%= form.fields_for :decisions do |decision_fields| %>
    <%= render "projects/project_decision_form", f: decision_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add">Add Decision</button>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Decision Project:</strong>
    <%= project.title %>
  </p>

  <%= form_for @DecisionInputs do |f| %>
  <% @values.each do |value| %>
    <div class="form-group">
      <%= f.label value %>
      <%= f.text_field value %>
    </div>
  <% end %>
  
  <%= f.submit "Submit" %>
<% end %>

  <p>
    <strong>Decision:</strong>
    <ul>
      <% project.decisions.each do |decision| %>
        <li>
          Input: <%= decision.input %>
          Input Type: <%= decision.input_type %>
        </li>
      <% end %>
    </ul>
  </p>

</div>

app/views/projects/_project_decision_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :input %>
  <%= f.text_field :input %>

  <%= f.label :input_type %>
  <%= f.text_field :input_type %>

  <button type="button" data-action="nested-form#remove">Remove Decision</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <p>
      <%= link_to project.title, project %>
    </p>
  <% end %>
</div>

<%= link_to "+New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>